#springcloud统一配置中心 
spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: test-provider-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: test-provider-test
    
#一定要另存为utf-8格式 否则会报错